Connet/timer
waderaku/pomodoro-frontend pull request #29
Opened 2022-05-06 00:57 UTC by kobayashi1227

# 注:このブランチはFix/package managerのプルリクを解決後マージしてください。
  
## timerコンポーネントとTaskManagerの結合
- 残タスク
  - Timerコンポーネントの構成を大きく変えたので、それに伴いstorybookの更新が必要(一旦古いのは消しました。)
  - 1clock何分かの設定ができ次第、一部ロジックを修正(一旦workのclockを25分、breakのclockを5分に設定)
  - MiniTimerの配置場所変更(どこがいいかな…)
  - hookのリファクタリング

2022-05-06 02:06 UTC, yotaro-shimose requested changes

2022-05-06 02:06 UTC, yotaro-shimose commented on src/domain/model.ts
> +  timerState: Timer;
〇〇Stateの命名規則をRecoilのAtom/Selector用にとっておいてあげてほしい。newTimerでどうでしょうか！

2022-05-07 02:43 UTC, waderaku commented on src/domain/hooks/windowDemention.ts
> +    const { innerWidth: width, innerHeight: height } = window;
あ、あと前回のプルリクでコメントしてる分も見直してね

2022-05-08 05:41 UTC, kobayashi1227 commented
FullWindowTimer
```html
        <Grid item>
          <div style={{ fontSize: "100px" }}>
            <span>{minutes}</span>:<span>{seconds}</span>
          </div>
        </Grid>
```
> Typographyってspanタグの代替ないんだっけ？
> 「：」だけspanタグに囲われてないのはなんでだ？ｗ

前PRのコメント取り込みました！

2022-05-08 06:00 UTC, kobayashi1227 commented on src/domain/model.ts
> +  timerWorking: string;
ユニオン型に定義しなおしました！

2022-05-08 06:01 UTC, kobayashi1227 commented on src/backendApi.ts
> +  const data = {
取り込みました！

2022-05-08 06:01 UTC, kobayashi1227 commented on src/component/TaskManager/TaskManager.tsx
> +import Timer from "./Timer/Timer";
取り込みました！

2022-05-08 06:01 UTC, kobayashi1227 commented on src/domain/model.ts
> +// };
消し忘れです…すみませぬ…

2022-05-08 06:01 UTC, kobayashi1227 commented on src/domain/model.ts
> +  timerState: Timer;
取り込みました！

2022-05-08 06:01 UTC, kobayashi1227 commented on src/component/TaskManager/Timer/Timer.tsx
> +  return <div />;
nullに直した！

2022-05-08 06:02 UTC, kobayashi1227 commented on src/domain/hooks/timerViewModels.ts
> +        setTime: !timer.isTask ? 25 * 60 : 5 * 60,
これはuserのカスタムhookで定義される予定だからその時直します！

2022-05-08 06:02 UTC, kobayashi1227 commented on src/domain/hooks/timerViewModels.ts
> +    timerWorking: "none",
ユニオン型にしたから許して('Д')

2022-05-08 06:03 UTC, kobayashi1227 commented on src/domain/hooks/timerViewModels.ts
> +        setTime: !timer.isTask ? 25 * 60 : 5 * 60,
前回PR指摘のhtmlの無名関数もこれと同じロジックだからuserのカスタムhookでき次第一緒に直す

2022-05-08 06:06 UTC, kobayashi1227 commented
指摘修正しました！再確認オナシャス！

2022-05-08 07:01 UTC, waderaku approved these changes

2022-05-08 13:23 UTC, yotaro-shimose approved these changes
ありがとうございます！

2022-05-09 23:05 UTC, merged